import { readFile, writeFile } from 'node:fs/promises';
import { createPublicClient, http, parseAbi, isAddress, zeroAddress } from 'viem';
const deployment = JSON.parse(await readFile('deployments/sepolia.json', 'utf8'));
if (deployment.mode !== 'testnet' || deployment.chainId !== 11155111 ||
    !isAddress(deployment.feeStrip) || deployment.feeStrip.toLowerCase() === zeroAddress ||
    !/^[1-9][0-9]*$/.test(deployment.deploymentBlock)) throw new Error('Invalid public Sepolia manifest');
const client = createPublicClient({ transport: http('https://ethereum-sepolia-rpc.publicnode.com', { timeout: 15000, retryCount: 1 }) });
if (await client.getChainId() !== deployment.chainId) throw new Error('RPC chain mismatch');
const blockNumber = await client.getBlockNumber();
const abi = parseAbi(['function poolManager() view returns(address)', 'function positionManager() view returns(address)', 'function usdc() view returns(address)', 'function nextSeriesId() view returns(uint256)']);
for (const name of ['poolManager', 'positionManager', 'usdc']) {
  const actual = await client.readContract({ address: deployment.feeStrip, abi, functionName: name, blockNumber });
  if (actual.toLowerCase() !== deployment[name].toLowerCase()) throw new Error('Public contract binding mismatch: ' + name);
}
const template = await readFile('packages/subgraph/subgraph.yaml', 'utf8');
if (!template.includes("address: '0x0000000000000000000000000000000000000000'") ||
    !template.includes('network: sepolia') || !template.includes("data: '11155111'")) throw new Error('Unexpected template scope');
const manifest = '# Generated by scripts/graph/prepare-sepolia.mjs from deployments/sepolia.json.\n' + template
  .replace("address: '0x0000000000000000000000000000000000000000'", `address: '${deployment.feeStrip.toLowerCase()}'`)
  .replace(/startBlock: [0-9]+/, `startBlock: ${deployment.deploymentBlock}`);
await writeFile('packages/subgraph/subgraph.sepolia.yaml', manifest);
console.log(JSON.stringify({ chainId: deployment.chainId, contract: deployment.feeStrip, startBlock: deployment.deploymentBlock, checkedAtBlock: blockNumber.toString(), nextSeriesId: (await client.readContract({ address: deployment.feeStrip, abi, functionName: 'nextSeriesId', blockNumber })).toString(), manifest: 'packages/subgraph/subgraph.sepolia.yaml' }));
