import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {encodeAbiParameters,parseAbiParameters,keccak256,toHex} from 'viem';
import {client,send,read,wallet,artifact,assertLocal} from './common.mjs';
import {acquireWitness} from './proof.mjs';
await assertLocal();
const d=JSON.parse(readFileSync('apps/web/public/deployment.json'));const {seller,buyer,holder}=d.actors;
const receipts=[];const tx=async(...args)=>{const r=await send(...args);receipts.push({function:args[3],hash:r.transactionHash,block:r.blockNumber.toString(),gas:r.gasUsed.toString()});return r;};
const balance=who=>read(d.usdc,'LocalToken','balanceOf',[who]);
const snapshot=()=>client.request({method:'evm_snapshot'});
const restore=id=>client.request({method:'evm_revert',params:[id]});
const nativeCollect=async(owner)=>{
 const snap=await snapshot();const before=await balance(holder);
 await client.request({method:'anvil_setBalance',params:[owner,toHex(10n**20n)]});
 await client.request({method:'anvil_impersonateAccount',params:[owner]});
 const [key]=await read(d.positionManager,'PositionManager','getPoolAndPositionInfo',[1n]);
 const p0=encodeAbiParameters(parseAbiParameters('uint256,uint256,uint128,uint128,bytes'),[1n,0n,0n,0n,'0x']);
 const p1=encodeAbiParameters(parseAbiParameters('address,address,address'),[key.currency0,key.currency1,holder]);
 const unlock=encodeAbiParameters(parseAbiParameters('bytes,bytes[]'),['0x0111',[p0,p1]]);
 const block=await client.getBlock();await send(owner,d.positionManager,'PositionManager','modifyLiquidities',[unlock,block.timestamp+3600n]);
 const amount=await balance(holder)-before;
 await client.request({method:'anvil_stopImpersonatingAccount',params:[owner]});assert.equal(await restore(snap),true);return amount;
};
const oldFees=await nativeCollect(seller);const sellerBefore=await balance(seller);
await tx(seller,d.positionManager,'PositionManager','approve',[d.feeStrip,1n]);
await tx(seller,d.feeStrip,'FeeStrip','acceptOffer',[1n,100_000_000n]);
assert.equal(await balance(seller)-sellerBefore,100_000_000n+oldFees);
assert.equal((await read(d.positionManager,'PositionManager','ownerOf',[1n])).toLowerCase(),d.feeStrip.toLowerCase());
let s=await read(d.feeStrip,'FeeStrip','series',[1n]);const claim=s.claim;
await tx(buyer,d.activityRouter,'LocalActivityRouter','donate',[800_000_000n,200_000_000n]);
// Real issued FeeClaim traded using official Aqua balance movement and FeeStrip extended runtime.
const now=await client.getBlock();
const order=await read(d.market,'FeeStripMarket','buildOrder',[1n,buyer,false,1000n*10n**18n,10_000_000n,Number(now.timestamp+3600n),'0x'+'01'.padStart(64,'0')]);
await tx(buyer,claim,'FeeClaim','approve',[d.aqua,7500n*10n**18n]);
await tx(buyer,d.usdc,'LocalToken','approve',[d.aqua,2n**256n-1n]);
const encodedOrder=encodeAbiParameters([{type:'tuple',components:[{name:'maker',type:'address'},{name:'traits',type:'uint256'},{name:'data',type:'bytes'}]}],[order]);
await tx(buyer,d.aqua,'Aqua','ship',[d.swapRouter,encodedOrder,[d.usdc,claim],[10_000_000n,7500n*10n**18n]]);
const takerData=await read(d.market,'FeeStripMarket','takerData',[holder,d.usdc,claim,1000n*10n**18n,Number(now.timestamp+3600n)]);
await tx(holder,d.usdc,'LocalToken','approve',[d.swapRouter,10_000_000n]);
const holderBefore=await balance(holder),makerBefore=await balance(buyer);
await tx(holder,d.swapRouter,'FeeStripRouter','swap',[order,10_000_000n,takerData]);
assert.equal(await balance(holder),holderBefore-10_000_000n);assert.equal(await balance(buyer),makerBefore+10_000_000n);
assert.equal(await read(claim,'FeeClaim','balanceOf',[holder]),1000n*10n**18n);
const end=BigInt(d.endBlock);const current=await client.getBlockNumber({cacheTime:0});
if(current>end)throw new Error('Local test missed N; reseed a fresh dedicated chain');
if(current<end)await client.request({method:'anvil_mine',params:[toHex(end-current)]});
const nativeAtN=await nativeCollect(d.feeStrip);
s=await read(d.feeStrip,'FeeStrip','series',[1n]);
const poolId=keccak256(encodeAbiParameters([{type:'tuple',components:[{name:'currency0',type:'address'},{name:'currency1',type:'address'},{name:'fee',type:'uint24'},{name:'tickSpacing',type:'int24'},{name:'hooks',type:'address'}]}],[s.key]));
const c0=s.key.currency0.toLowerCase()===d.usdc.toLowerCase();
const slots=await read(d.verifier,'HistoricalFeeVerifier','storageSlots',[poolId,s.tickLower,s.tickUpper,c0]);
const retained=await acquireWitness(client,{manager:d.poolManager,slots,blockNumber:end});
writeFileSync('apps/web/public/witness-1.json',JSON.stringify(retained,null,2)+'\n');
await client.request({method:'anvil_mine',params:['0x1']});
await tx(buyer,d.activityRouter,'LocalActivityRouter','donate',[400_000_000n,100_000_000n]);
await tx(holder,d.feeStrip,'FeeStrip','capture',[1n]);
s=await read(d.feeStrip,'FeeStrip','series',[1n]);assert.ok(s.capturedUSDC>nativeAtN);
await tx(seller,d.feeStrip,'FeeStrip','withdrawNFT',[1n,seller]);
assert.equal((await read(d.positionManager,'PositionManager','ownerOf',[1n])).toLowerCase(),seller.toLowerCase());
assert.equal((await read(d.feeStrip,'FeeStrip','series',[1n])).allocated,false);
await tx(holder,d.checkpoints,'BlockHashCheckpoints','checkpoint',[end]);
await tx(holder,d.feeStrip,'FeeStrip','settle',[1n,retained.witness]);
s=await read(d.feeStrip,'FeeStrip','series',[1n]);assert.equal(s.soldUSDC,nativeAtN,'authenticated allocation equals independent N-native collection');
let totalPaid=0n;const payouts=[];
for(const actor of [holder,buyer,seller]){const q=await read(claim,'FeeClaim','balanceOf',[actor]);const before=await balance(actor);await tx(actor,d.feeStrip,'FeeStrip','redeem',[1n,q,actor]);const paid=await balance(actor)-before;assert.equal(paid,nativeAtN*q/s.quantity);totalPaid+=paid;payouts.push({actor,quantity:q.toString(),usdc:paid.toString()});}
const residualBefore=await balance(seller);await tx(seller,d.feeStrip,'FeeStrip','withdrawResidual',[1n,seller]);
assert.equal(await balance(seller)-residualBefore,s.capturedUSDC-nativeAtN);
assert.equal(await read(claim,'FeeClaim','totalSupply'),0n);
assert.equal(await read(d.feeStrip,'FeeStrip','reservedUSDC'),nativeAtN-totalPaid);
assert.equal(await balance(d.feeStrip),nativeAtN-totalPaid);
const evidence={scope:'actual local Anvil transactions; canonical Uniswap sources, local faucet currencies; real header/account/storage verifier. Not public-chain FeeStrip deployment.',chainId:31337,endpointBlock:d.endBlock,endpointHash:retained.blockHash,oldFees:oldFees.toString(),nativeAtN:nativeAtN.toString(),capturedUSDC:s.capturedUSDC.toString(),residualUSDC:(s.capturedUSDC-nativeAtN).toString(),dust:(nativeAtN-totalPaid).toString(),payouts,receipts,contracts:d};
mkdirSync('docs/evidence',{recursive:true});writeFileSync('docs/evidence/local-lifecycle.json',JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({result:'passed',nativeAtN:evidence.nativeAtN,captured:evidence.capturedUSDC,dust:evidence.dust,transactions:receipts.length}));
