import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {client,send,deploy,read,assertLocal,rpcURL} from './common.mjs';
await assertLocal();
const accounts=await client.request({method:'eth_accounts'});
const [seller,buyer,holder]=accounts;
const broadcast=JSON.parse(readFileSync('broadcast/DeployLocalNative.s.sol/31337/run-latest.json'));
const created=broadcast.transactions.filter(t=>t.transactionType==='CREATE');
const address=name=>created.find(t=>t.contractName===name)?.contractAddress;
const poolManager=address('PoolManager'),positionManager=address('PositionManager');
const usdc=created.find(t=>t.contractName==='LocalToken'&&t.arguments[1]==='USDC').contractAddress;
const other=created.find(t=>t.contractName==='LocalToken'&&t.arguments[1]==='TEST').contractAddress;
const activityRouter=address('LocalActivityRouter');
if((await read(positionManager,'PositionManager','ownerOf',[1n])).toLowerCase()!==seller.toLowerCase())throw new Error('Native fixture does not match this local chain; deploy on a fresh dedicated node');
const checkpoints=await deploy(seller,'BlockHashCheckpoints');
const verifier=await deploy(seller,'HistoricalFeeVerifier',[poolManager,checkpoints]);
const feeStrip=await deploy(seller,'FeeStrip',[positionManager,usdc,verifier]);
const aqua=await deploy(seller,'Aqua');
const swapRouter=await deploy(seller,'FeeStripRouter',[aqua,'0x0000000000000000000000000000000000000000',seller]);
const market=await deploy(seller,'FeeStripMarket',[feeStrip,swapRouter]);
for(const token of [usdc,other])await send(buyer,token,'LocalToken','approve',[activityRouter,2n**256n-1n]);
await send(buyer,activityRouter,'LocalActivityRouter','donate',[123_000_000n,45_000_000n]);
await send(seller,usdc,'LocalToken','mint',[holder,50_000_000_000n]);
await send(buyer,usdc,'LocalToken','approve',[feeStrip,100_000_000n]);
const block=await client.getBlock();const endBlock=block.number+100n;
const commitment=await read(feeStrip,'FeeStrip','positionCommitment',[1n]);
await send(buyer,feeStrip,'FeeStrip','fundOffer',[seller,1n,10000n*10n**18n,7500n*10n**18n,100_000_000n,endBlock,block.timestamp+86400n,commitment]);
const config={mode:'local',chainId:31337,rpcUrl:rpcURL,feeStrip,usdc,other,positionManager,poolManager,verifier,checkpoints,market,swapRouter,aqua,activityRouter,nftIds:['1'],actors:{seller,buyer,holder},offerId:'1',endBlock:endBlock.toString(),deploymentBlock:broadcast.receipts[0].blockNumber};
mkdirSync('apps/web/public',{recursive:true});writeFileSync('apps/web/public/deployment.json',JSON.stringify(config,null,2)+'\n');
mkdirSync('.scratch',{recursive:true});writeFileSync('.scratch/local-deployment.json',JSON.stringify(config,null,2)+'\n');
console.log(`Local fixture ready: NFT1, funded offer1, end block ${endBlock}. Approve and accept through the app or lifecycle command.`);
